"""
Pydantic models for OpenAI Chat Completions API

Reference: https://platform.openai.com/docs/api-reference/chat
"""
from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Dict, Any, Union, Literal
from enum import Enum


class ChatCompletionRole(str, Enum):
    """Role of the message author"""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    FUNCTION = "function"  # Deprecated but still supported


class FinishReason(str, Enum):
    """Reason why the model stopped generating tokens"""
    STOP = "stop"  # Model hit a natural stop point or provided stop sequence
    LENGTH = "length"  # Maximum number of tokens specified in the request was reached
    CONTENT_FILTER = "content_filter"  # Content was omitted due to a flag from content filters
    TOOL_CALLS = "tool_calls"  # Model called a tool
    FUNCTION_CALL = "function_call"  # Deprecated in favor of tool_calls


class ChatCompletionMessageToolCallType(str, Enum):
    """Type of tool call"""
    FUNCTION = "function"


class ChatCompletionMessageToolCallFunction(BaseModel):
    """Function call details within a tool call"""
    name: str = Field(..., description="The name of the function to call.")
    arguments: str = Field(..., description="The arguments to call the function with, as generated by the model in JSON format.")


class ChatCompletionMessageToolCall(BaseModel):
    """Tool call made by the model"""
    id: str = Field(..., description="The ID of the tool call.")
    type: ChatCompletionMessageToolCallType = Field(..., description="The type of the tool. Currently, only 'function' is supported.")
    function: ChatCompletionMessageToolCallFunction = Field(..., description="The function that the model called.")


class ChatCompletionMessageFunctionCall(BaseModel):
    """Deprecated function call (use tool_calls instead)"""
    name: str = Field(..., description="The name of the function to call.")
    arguments: str = Field(..., description="The arguments to call the function with, as generated by the model in JSON format.")


class ChatCompletionMessage(BaseModel):
    """Message generated by the model"""
    role: ChatCompletionRole = Field(..., description="The role of the author of this message.")
    content: Optional[str] = Field(None, description="The contents of the message.")
    refusal: Optional[str] = Field(None, description="The refusal message generated by the model.")
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = Field(
        None, 
        description="The tool calls generated by the model, such as function calls."
    )
    function_call: Optional[ChatCompletionMessageFunctionCall] = Field(
        None,
        description="Deprecated and replaced by tool_calls. The name and arguments of a function that should be called, as generated by the model.",
        deprecated=True
    )


class TopLogprob(BaseModel):
    """Log probability information for a token"""
    token: str = Field(..., description="The token.")
    logprob: float = Field(..., description="The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value -9999.0 is used to signify that the token is very unlikely.")
    bytes: Optional[List[int]] = Field(None, description="A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be null if there is no bytes representation for the token.")


class ChatCompletionTokenLogprob(BaseModel):
    """Log probability information"""
    token: str = Field(..., description="The token.")
    logprob: float = Field(..., description="The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value -9999.0 is used to signify that the token is very unlikely.")
    bytes: Optional[List[int]] = Field(None, description="A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be null if there is no bytes representation for the token.")
    top_logprobs: List[TopLogprob] = Field(..., description="List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested top_logprobs returned.")


class ChatCompletionChoiceLogprobs(BaseModel):
    """Log probability information for the choice"""
    content: Optional[List[ChatCompletionTokenLogprob]] = Field(
        None,
        description="A list of message content tokens with log probability information."
    )
    refusal: Optional[List[ChatCompletionTokenLogprob]] = Field(
        None,
        description="A list of message refusal tokens with log probability information."
    )


class ChatCompletionChoice(BaseModel):
    """A chat completion choice generated by the model"""
    index: int = Field(..., description="The index of the choice in the list of choices.")
    message: ChatCompletionMessage = Field(..., description="A chat completion message generated by the model.")
    logprobs: Optional[ChatCompletionChoiceLogprobs] = Field(
        None,
        description="Log probability information for the choice."
    )
    finish_reason: FinishReason = Field(
        ...,
        description="The reason the model stopped generating tokens. This will be 'stop' if the model hit a natural stop point or a provided stop sequence, 'length' if the maximum number of tokens specified in the request was reached, 'content_filter' if content was omitted due to a flag from our content filters, 'tool_calls' if the model called a tool, or 'function_call' (deprecated) if the model called a function."
    )


class CompletionUsage(BaseModel):
    """Usage statistics for the completion request"""
    prompt_tokens: int = Field(..., description="Number of tokens in the prompt.")
    completion_tokens: int = Field(..., description="Number of tokens in the generated completion.")
    total_tokens: int = Field(..., description="Total number of tokens used in the request (prompt + completion).")
    prompt_tokens_details: Optional[Dict[str, int]] = Field(
        None,
        description="Breakdown of tokens in the prompt."
    )
    completion_tokens_details: Optional[Dict[str, int]] = Field(
        None,
        description="Breakdown of tokens in the completion."
    )


class ChatCompletion(BaseModel):
    """
    Represents a chat completion response returned by model, based on the provided input.
    
    Reference: https://platform.openai.com/docs/api-reference/chat/object
    """
    id: str = Field(..., description="A unique identifier for the chat completion.")
    object: Literal["chat.completion"] = Field(
        default="chat.completion",
        description="The object type, which is always 'chat.completion'."
    )
    created: int = Field(..., description="The Unix timestamp (in seconds) of when the chat completion was created.")
    model: str = Field(..., description="The model used for the chat completion.")
    choices: List[ChatCompletionChoice] = Field(..., description="A list of chat completion choices. Can be more than one if n is greater than 1.")
    usage: Optional[CompletionUsage] = Field(None, description="Usage statistics for the completion request.")
    system_fingerprint: Optional[str] = Field(
        None,
        description="This fingerprint represents the backend configuration that the model runs with. Can be used in conjunction with the seed request parameter to understand when backend changes have been made that might impact determinism."
    )
    service_tier: Optional[str] = Field(
        None,
        description="The service tier used for processing the request. This field is only included if the service_tier parameter is specified in the request."
    )

    class Config:
        use_enum_values = True
        json_schema_extra = {
            "example": {
                "id": "chatcmpl-123",
                "object": "chat.completion",
                "created": 1677652288,
                "model": "gpt-4o-mini",
                "choices": [
                    {
                        "index": 0,
                        "message": {
                            "role": "assistant",
                            "content": "Hello! How can I assist you today?",
                            "refusal": None
                        },
                        "logprobs": None,
                        "finish_reason": "stop"
                    }
                ],
                "usage": {
                    "prompt_tokens": 9,
                    "completion_tokens": 12,
                    "total_tokens": 21,
                    "completion_tokens_details": {
                        "reasoning_tokens": 0,
                        "accepted_prediction_tokens": 0,
                        "rejected_prediction_tokens": 0
                    }
                },
                "system_fingerprint": "fp_44709d6fcb"
            }
        }


# ============================================================================
# Streaming Chat Completion Models
# ============================================================================

class ChatCompletionStreamChoiceDelta(BaseModel):
    """Delta content in streaming response"""
    role: Optional[ChatCompletionRole] = Field(None, description="The role of the author of this message.")
    content: Optional[str] = Field(None, description="The contents of the chunk message.")
    refusal: Optional[str] = Field(None, description="The refusal message generated by the model.")
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = Field(
        None,
        description="The tool calls generated by the model, such as function calls."
    )
    function_call: Optional[ChatCompletionMessageFunctionCall] = Field(
        None,
        description="Deprecated and replaced by tool_calls.",
        deprecated=True
    )


class ChatCompletionStreamChoice(BaseModel):
    """A chat completion choice in a streaming response"""
    index: int = Field(..., description="The index of the choice in the list of choices.")
    delta: ChatCompletionStreamChoiceDelta = Field(..., description="A chat completion delta generated by streamed model responses.")
    logprobs: Optional[ChatCompletionChoiceLogprobs] = Field(
        None,
        description="Log probability information for the choice."
    )
    finish_reason: Optional[FinishReason] = Field(
        None,
        description="The reason the model stopped generating tokens. This will be 'stop' if the model hit a natural stop point or a provided stop sequence, 'length' if the maximum number of tokens specified in the request was reached, 'content_filter' if content was omitted due to a flag from our content filters, 'tool_calls' if the model called a tool, or 'function_call' (deprecated) if the model called a function."
    )


class ChatCompletionChunk(BaseModel):
    """
    Represents a streamed chunk of a chat completion response returned by model, based on the provided input.
    
    Reference: https://platform.openai.com/docs/api-reference/chat/streaming
    """
    id: str = Field(..., description="A unique identifier for the chat completion. Each chunk has the same ID.")
    object: Literal["chat.completion.chunk"] = Field(
        default="chat.completion.chunk",
        description="The object type, which is always 'chat.completion.chunk'."
    )
    created: int = Field(..., description="The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.")
    model: str = Field(..., description="The model used for the chat completion.")
    choices: List[ChatCompletionStreamChoice] = Field(..., description="A list of chat completion choices. Can be more than one if n is greater than 1.")
    usage: Optional[CompletionUsage] = Field(
        None,
        description="An optional field that will only be present when you set stream_options: {\"include_usage\": true} in your request. When present, it contains a null value except for the last chunk which contains the token usage statistics for the entire request."
    )
    system_fingerprint: Optional[str] = Field(
        None,
        description="This fingerprint represents the backend configuration that the model runs with. Can be used in conjunction with the seed request parameter to understand when backend changes have been made that might impact determinism."
    )
    service_tier: Optional[str] = Field(
        None,
        description="The service tier used for processing the request."
    )

    class Config:
        use_enum_values = True
        json_schema_extra = {
            "example": {
                "id": "chatcmpl-123",
                "object": "chat.completion.chunk",
                "created": 1694268190,
                "model": "gpt-4o-mini",
                "system_fingerprint": "fp_44709d6fcb",
                "choices": [
                    {
                        "index": 0,
                        "delta": {
                            "role": "assistant",
                            "content": ""
                        },
                        "logprobs": None,
                        "finish_reason": None
                    }
                ]
            }
        }
